sh ./batchTest.sh testCases/perf_2_$1.txt
sh ./batchTest.sh testCases/perf_3_$1.txt
sh ./batchTest.sh testCases/perf_4_$1.txt
sh ./batchTest.sh testCases/perf_5_$1.txt
sh ./batchTest.sh testCases/perf_6_$1.txt
sh ./batchTest.sh testCases/perf_7_$1.txt
sh ./batchTest.sh testCases/perf_8_$1.txt
sh ./batchTest.sh testCases/perf_9_$1.txt
sh ./batchTest.sh testCases/perf_10_$1.txt
sh ./batchTest.sh testCases/perf_11_$1.txt
sh ./batchTest.sh testCases/perf_12_$1.txt
sh ./batchTest.sh testCases/perf_13_$1.txt
sh ./batchTest.sh testCases/perf_14_$1.txt
sh ./batchTest.sh testCases/perf_15_$1.txt
sh ./batchTest.sh testCases/perf_16_$1.txt
